name: Set up SSH Server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install OpenSSH Server
      run: sudo apt-get update && sudo apt-get install -y openssh-server
    - name: Start SSH server
      run: sudo systemctl start ssh
