name: Set up SSH Server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install OpenSSH Server
      run: sudo apt-get update && sudo apt-get install -y openssh-server
    - name: Start SSH server
      run: sudo systemctl start ssh
    - name: Print connection information
      run: echo "Username: ubuntu" && echo "Password: $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1)"
      id: ssh_credentials
    - name: Get IP address
      run: ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
      id: ssh_ip
    - name: Connect to server
      run: ssh ubuntu@${{ steps.ssh_ip.output }}
      env:
        SSH_AUTH_SOCK: /tmp/ssh_auth_sock
      env:
        SSH_AUTH_SOCK: /tmp/ssh_auth_sock
      env:
        SSH_ASKPASS: 'echo "{{steps.ssh_credentials.output}}" | grep "Password:" | awk "{print \$2}"'
